Added alita script

diff --git a/alita/scripts/alita b/alita/scripts/alita
--- a/alita/scripts/alita
+++ b/alita/scripts/alita
@@ -17,16 +17,16 @@ CONTROL_HOST="baley"
 #*****************
 
 # SocketCAN interfaces
-BUS_1_L=0 # Left arm
-BUS_2_L=1 # Left arm
+BUS_1_L=0 # Left arm first bus (first 4 modules)
+BUS_2_L=1 # Left arm second bus (last 3 modules + gripper)
 BUS_1_R=2 # Right arm first bus (first 4 modules)
 BUS_2_R=3 # Right arm second bus (last 3 modules + gripper)
 
 
 # Check where SNS is located
 if test -z $SNS; then
-    if test -x /home/ana/local/etc/init.d/sns; then
-	SNS=/home/ana/local/etc/init.d/sns
+    if test -x ${HOME}/local/etc/init.d/sns; then
+	SNS=${HOME}/local/etc/init.d/sns
     elif test -x /usr/local/etc/init.d/sns; then
 	SNS=/usr/local/etc/init.d/sns
     elif test -x /etc/init.d/sns; then
@@ -40,6 +40,33 @@ fi
 #**************
 # FUNCTIONS
 #**************
+
+# Load drivers
+alita_load_drivers() {
+
+    # Load esdcan module
+    lsmod | grep -q esdcan
+    if [ $? -eq 1 ]
+    then
+      echo "esdcan module is not loaded yet";
+      cd /usr/src/esdcan-pci405-linux-2.6.x-x86_64-3.9.5/src
+      sudo insmod esdcan-pci405.ko
+    else
+      echo "esdcan module is already loaded"
+    fi
+    # Create device files can0/1/2/3
+    cd /dev
+    for i in `seq 0 3`
+    do
+      name="can${i}";
+      if ! [ -e $name ]
+      then
+        sudo mknod --mode=a+rw $name c 53 $i
+      fi
+    done
+
+  echo "Finished alita_load_drivers";
+}
 
 # Make channels
 alita_ach_mk() {
@@ -80,7 +107,7 @@ alita_start_sns() {
 
 # Start : Create channels + start SNS + run daemons
 alita_start() {
-    crichton_ach_mk
+    alita_ach_mk
 
     # Pull arm/hand states
 #    $SNS run -d push_state_left -- \
@@ -89,30 +116,30 @@ alita_start() {
 #    $SNS run -d push_state_right -- \
     achd -d push $PLANNING_HOST state-right	
 
-#		$SNS run -d push_sdhstate_left -- \
+#   $SNS run -d push_gripstate_left -- \
     achd -d push $PLANNING_HOST gripstate-left 	
    
-#		$SNS run -d push_sdhstate_right -- \
-		achd -d push $PLANNING_HOST gripstate-right	
+#   $SNS run -d push_gripstate_right -- \
+    achd -d push $PLANNING_HOST gripstate-right	
 
-#		$SNS run -d pull_bimanual_chan -- \
-	  achd -d pull $PLANNING_HOST bimanual_chan
+#   $SNS run -d pull_bimanual_chan -- \
+    achd -d pull $PLANNING_HOST bimanual_chan
 
 #    $SNS run -d pull_bimanual_hand_chan -- \
-		achd -d pull $PLANNING_HOST bimanual_hand_chan
+    achd -d pull $PLANNING_HOST bimanual_hand_chan
 
     # Run daemons
     $SNS run -d -r lwa-left -- \
-		can402 -f $CAN_L -R 1 -C 0 -n 3 -n 4 -n 5 -n 6 -n 7 -n 8 -n 9 -c ref-left -s state-left 
+    pcio-sns -c ref-left -s state-left -b $BUS_1_L -m 1 -m 2 -m 3 -m 4 -b $BUS_2_L -m 5 -m 6 -m 7  
 
-     $SNS run  -d -r sdh-left -- \
-     sdhiod -b $CAN_SDH_L -c sdhref-left -s sdhstate-left
+     $SNS run  -d -r grip-left -- \
+     pcio-sns -c gripref-left -s gripstate-left  -b $BUS_2_L -m 8 -H 
 
-     $SNS run -d -r lwa-right -- \
-     can402 -f $CAN_R -R 1 -C 0 -n 3 -n 4 -n 5 -n 6 -n 7 -n 8 -n 9 -c ref-right -s state-right    
+    $SNS run -d -r lwa-right -- \
+    pcio-sns -c ref-right -s state-right -b $BUS_1_R -m 1 -m 2 -m 3 -m 4 -b $BUS_2_R -m 5 -m 6 -m 7  
 
-     $SNS run  -d -r sdh-right -- \
-     sdhiod -b $CAN_SDH_R -c sdhref-right -s sdhstate-right
+     $SNS run  -d -r grip-right -- \
+     pcio-sns -c gripref-right -s gripstate-right  -b $BUS_2_L -m 8 -H 
 
 }
 
@@ -121,47 +148,47 @@ alita_expunge() {
     sudo rm -rf /var/tmp/sns/lwa-left
     sudo rm -rf /var/run/sns/lwa-left
 
-    sudo rm -rf /var/tmp/sns/sdh-left
-    sudo rm -rf /var/run/sns/sdh-left
+    sudo rm -rf /var/tmp/sns/grip-left
+    sudo rm -rf /var/run/sns/grip-left
     
-		sudo rm -rf /var/tmp/sns/lwa-right
+    sudo rm -rf /var/tmp/sns/lwa-right
     sudo rm -rf /var/run/sns/lwa-right
  
-		sudo rm -rf /var/tmp/sns/sdh-right
-    sudo rm -rf /var/run/sns/sdh-right
+    sudo rm -rf /var/tmp/sns/grip-right
+    sudo rm -rf /var/run/sns/grip-right
 
 
-		sudo rm -rf /var/tmp/sns/push_state_left
+    sudo rm -rf /var/tmp/sns/push_state_left
     sudo rm -rf /var/run/sns/push_state_left
 		
-		sudo rm -rf /var/tmp/sns/push_state_right
+    sudo rm -rf /var/tmp/sns/push_state_right
     sudo rm -rf /var/run/sns/push_state_right
 
-		sudo rm -rf /var/tmp/sns/push_sdhstate_left
-    sudo rm -rf /var/run/sns/push_sdhstate_left
+    sudo rm -rf /var/tmp/sns/push_gripstate_left
+    sudo rm -rf /var/run/sns/push_gripstate_left
 		
-		sudo rm -rf /var/tmp/sns/push_sdhstate_right
-    sudo rm -rf /var/run/sns/push_sdhstate_right
+    sudo rm -rf /var/tmp/sns/push_gripstate_right
+    sudo rm -rf /var/run/sns/push_gripstate_right
 
 
-		sudo rm -rf /var/tmp/sns/pull_bimanual_chan
+    sudo rm -rf /var/tmp/sns/pull_bimanual_chan
     sudo rm -rf /var/run/sns/pull_bimanual_chan
 		
-		sudo rm -rf /var/tmp/sns/pull_bimanual_hand_chan
+    sudo rm -rf /var/tmp/sns/pull_bimanual_hand_chan
     sudo rm -rf /var/run/sns/pull_bimanual_hand_chan
 }
 
 
 # Stop: Stop daemons and programs
-crichton_stop() {
+alita_stop() {
     $SNS kill lwa-left
-    $SNS kill sdh-left
+    $SNS kill grip-left
     $SNS kill lwa-right
-    $SNS kill sdh-right
+    $SNS kill grip-right
 
     $SNS kill push_state_left
-		$SNS kill push_state_right
-		$SNS kill push_sdhstate_left
+    $SNS kill push_state_right
+    $SNS kill push_sdhstate_left
     $SNS kill push_sdhstate_right
     $SNS kill pull_bimanual_chan
     $SNS kill pull_bimanual_hand_chan
@@ -169,40 +196,42 @@ crichton_stop() {
 }
 
 # Change ownerships of SNS temporal files
-crichton_steal() {
+alita_steal() {
     chown -R $1 /var/run/sns/lwa-left \
 	/var/tmp/sns/lwa-left \
-	/var/run/sns/sdh-left \
-	/var/tmp/sns/sdh-left \
+	/var/run/sns/grip-left \
+	/var/tmp/sns/grip-left \
 	/var/run/sns/lwa-right \
 	/var/tmp/sns/lwa-right \
-  /var/run/sns/sdh-right \
-  /var/tmp/sns/sdh-right \
- 
+  	/var/run/sns/grip-right \
+  	/var/tmp/sns/grip-right \
 }
 
 #***************************
 # SET SCRIPT OPTIONS
 #***************************
 case "$1" in
+    load)
+         alita_load_drivers
+	 ;;
     start)
-	crichton_start
+	alita_start
 	;;
     stop)
-	crichton_stop
+	alita_stop
 	;;
     rm) 
-	crichton_ach_rm
+	alita_ach_rm
 	;;
     mk)
-	crichton_ach_mk
+	alita_ach_mk
 	;;
     steal)
 	shift
-	crichton_steal $@
+	alita_steal $@
 	;;
     expunge)
-	crichton_expunge
+	alita_expunge
 	;;
 	  zero)
   	echo "-- Sending zero velocity to left arm"
@@ -213,7 +242,7 @@ case "$1" in
   	sleep 2
 	;;	
     *)
-	echo "[ERROR] Invalid command. Options are start/stop/rm/mk/steal/zero NEW_OWNER/expunge"
+	echo "[ERROR] Invalid command. Options are load/start/stop/rm/mk/steal/zero NEW_OWNER/expunge"
 	exit 1
 	;;
 esac
